[package]
name = "entro_gd"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
csv = "1.4.0"
log = "0.4.29"
env_logger = "0.11.9"
flexi_logger = "0.31.8"
chrono = "0.4.43"

[dev-dependencies]
criterion = "0.8.2"
pretty_assertions = "1.4.1"

[[bench]]
name = "benchmark_individual"
harness = false